name: vfxplainer
description: "An interactive visual effects explainer app built with Flutter."
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ^3.6.1

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.6
    go_router: ^15.1.2
    flutter_svg: ^2.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/svgs/
        - assets/images/
